### PR TITLE
Update _multiple.scss

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by apalfrey** [comment]
This doesn't compile due to the mixing of `em` and `rem` units which `max()` doesn't allow for with node-sass.

I've attached the file with the errors that occur during compiling.

[24.log](https://github.com/apalfrey/select2-bootstrap-5-theme/files/6468160/24.log)

If you can find a solution, please push to the pull request again, let me know and I'll take a look at it again.

Also, if you could commit the compiled files to the PR that would be a great help, along with a comment explaining what this is meant to achieve.

**Comment by WinterSilence** [comment]
@apalfrey it's change only `display` attribute

**Comment by apalfrey** [comment]
Hi @WinterSilence I'm sorry, I must have mixed up your 2 pull requests! I'll get the right comments and states sorted now.

**Comment by apalfrey** [comment]
The correct message:

This completely removes the searching functionality for the multiple select fields.

As this essentially removes functionality from Select2, I can't add this to the theme.

If this isn't what you wanted to achieve, comment on this again to let me know and I'll reopen it to let you make whatever changes are necessary.

**Comment by WinterSilence** [comment]
@apalfrey hm... I didn't know about the search, need add placeholder or border to mark it

**Pull request closed without merging**
