### PR TITLE
composer support added

### PR DESCRIPTION
**Pull request by f1mishutka**
I'll also change path to repository to the original at the packagist after PR is accepted.

https://packagist.org/packages/apalfrey/select2-bootstrap-5-theme

You can also register at packagist for I to be able to add you as package maintainer.

Thank you!

### CODE REVIEW

**Comment by apalfrey** [comment]
That's brilliant, thanks so much! I've not really had any experience with composer, so if you have any way to improve it for composer, either let me know or feel free to submit a pull request! I'll go ahead and merge this now

**Comment by f1mishutka** [comment]
Thank you for your efforts!

I've changed repo path to original one (https://github.com/apalfrey/select2-bootstrap-5-theme) at packagist.
Will keep an eye on it :)

**Comment by f1mishutka** [comment]
You'll need to release new version (1.0.2) with separate tag for packagist to scan it. Repo at tag "1.0.1" does not contains composer.json because it was created before this merge. So it will be fully integrated with packagist (with version auto-updates) after you add "1.0.2" tag.

**Comment by apalfrey** [comment]
Ah, no worries, I'll get that sorted for you now! And thanks again

**Pull request merged**
